#!/bin/bash

# Attach the loop device for copying
# initial boot environment
boot="bochs/boot"
img="hdd.img"
offset="0"
if [ "$1" == "-o" ]; then
	if [ "$2" != "" ]; then
		offset="$2"
	fi
fi
echo "Setting up loop device on /dev/loop0"
echo "from $boot/$img +$offset bytes"
sudo losetup /dev/loop0 $boot/$img -o$offset
